minimumReleaseAgeExclude:
  - '@solidjs/babel-plugin@2.0.0-rc.8'
  - '@solidjs/compiler-darwin-arm64@2.0.0-rc.8'
  - '@solidjs/compiler-darwin-x64@2.0.0-rc.8'
  - '@solidjs/compiler-linux-arm64-gnu@2.0.0-rc.8'
  - '@solidjs/compiler-linux-x64-gnu@2.0.0-rc.8'
  - '@solidjs/compiler-wasm32-wasi@2.0.0-rc.8'
  - '@solidjs/compiler-win32-x64-msvc@2.0.0-rc.8'
  - '@solidjs/compiler@2.0.0-rc.8'
  - '@solidjs/signals@2.0.0-rc.8'
  - '@solidjs/vite-plugin@3.0.0-next.43'
  - '@solidjs/web@2.0.0-rc.8'
  - solid-js@2.0.0-rc.8
