[package]
name = "mediaar"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Manage your media"
readme = "README.md"
repository = "https://github.com/ggallovalle/mediaar"
homepage = "https://github.com/ggallovalle/mediaar"
keywords = ["media", "tui", "desktop", "gpui"]
categories = ["command-line-utilities", "gui"]
default-run = "mediaar"
include = [
  "src/**/*",
  "locales/**/*",
  "icons/**/*",
  "README.md",
]

[[bin]]
name = "mediaar"
path = "src/main.rs"

[dependencies]
catppuccin = { workspace = true }
crossterm = { workspace = true }
fluent = { workspace = true }
gpui = { workspace = true }
ratatui = { workspace = true }
unic-langid = { workspace = true }
usage = { workspace = true }
usage-config = { workspace = true }

[dev-dependencies]
usage = { package = "usage-rs", version = "6", features = ["test"] }

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version }-{ target }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"
